"""is_shared file

Revision ID: 35be231a4302
Revises: 522dff56ec4d
Create Date: 2018-06-12 18:44:32.389162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35be231a4302'
down_revision = '522dff56ec4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('is_shared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'is_shared')
    # ### end Alembic commands ###
