"""empty message

Revision ID: 490edaea13dc
Revises: 
Create Date: 2019-06-02 13:49:58.550589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490edaea13dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('file', sa.Column('filepath_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'file', ['filepath_id'], ['id'])
    op.drop_column('file', 'filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filepath', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'filepath_id')
    op.drop_table('file_path')
    # ### end Alembic commands ###
