"""uploadtime

Revision ID: 522dff56ec4d
Revises: d1c50ffd3f1f
Create Date: 2018-06-12 16:31:09.536192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522dff56ec4d'
down_revision = 'd1c50ffd3f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploadtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'uploadtime')
    # ### end Alembic commands ###
