"""sharelink added to user

Revision ID: fd756abb756a
Revises: 35be231a4302
Create Date: 2018-06-13 00:24:01.041084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd756abb756a'
down_revision = '35be231a4302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sharelink', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['sharelink'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'sharelink')
    # ### end Alembic commands ###
